# Generated by Django 5.0.3 on 2024-04-04 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(max_length=30, unique=True, verbose_name='Город')),
                ('country', models.CharField(max_length=30, unique=True, verbose_name='Страна')),
                ('with_photo', models.BooleanField()),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('volume', models.FloatField()),
                ('box', models.CharField(choices=[('Автомат', 'Автомат'), ('Механика', 'Механика')], max_length=10, verbose_name='Коробка')),
                ('drivetrain', models.CharField(choices=[('Передний', 'Передний'), ('Задний', 'Задний'), ('4WD', '4WD')], max_length=10)),
                ('engine', models.CharField(choices=[('Бензин', 'Бензин'), ('Газ', 'Газ'), ('Электро', 'Электро'), ('Гибрид', 'Гибрид')], max_length=10)),
                ('description', models.CharField(max_length=10, verbose_name='Комментарии')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_marka', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_bet', models.IntegerField(default=0, verbose_name='Цена ставки')),
                ('total_price', models.IntegerField(default=0)),
                ('buy_now', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('car_bet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_photo/', verbose_name='Изображение')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='car',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.marka', verbose_name='Марка'),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_model', models.CharField(max_length=16, unique=True, verbose_name='Марка')),
                ('marka_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.marka')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.model', verbose_name='Модель'),
        ),
    ]
