# Generated by Django 5.0.3 on 2024-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='title_model',
            field=models.CharField(max_length=16, unique=True, verbose_name='Модель'),
        ),
    ]
