# Generated by Django 5.0.3 on 2024-04-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_model_title_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.FloatField(default=0.8, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Выпуск года'),
        ),
        migrations.AlterField(
            model_name='marka',
            name='title_marka',
            field=models.CharField(max_length=16, unique=True, verbose_name='Марка'),
        ),
    ]
