# Generated by Django 5.0.3 on 2024-04-04 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_description_alter_car_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='buy_now',
            field=models.IntegerField(default=0, verbose_name='Фикцированная сумма'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='car_bet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Выбрать машины'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Общая стоимость'),
        ),
    ]
