# Generated by Django 5.0.3 on 2024-04-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_bet_buy_now_alter_bet_car_bet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='car',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='car',
            name='city_en',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='car',
            name='city_ru',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='car',
            name='country_en',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='car',
            name='country_ru',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='car',
            name='marka_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.marka', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='car',
            name='marka_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.marka', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.model', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.model', verbose_name='Модель'),
        ),
    ]
