# Generated by Django 5.0.3 on 2024-04-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_car_category_en_car_category_ru_car_city_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Пробег'),
        ),
    ]
