# Generated by Django 5.0.3 on 2024-04-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(null=True, verbose_name='Комментарии'),
        ),
    ]
