# Generated by Django 5.0.3 on 2024-04-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.CharField(null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.CharField(null=True, verbose_name='Комментарии'),
        ),
    ]
