# Generated by Django 5.0.3 on 2024-04-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_car_description_en_car_description_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
