# Generated by Django 5.0.3 on 2024-04-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.BooleanField(default=0.8, verbose_name='Объем'),
        ),
    ]
