# Generated by Django 5.0.3 on 2024-04-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_car_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.BooleanField(verbose_name='Объем'),
        ),
    ]
