# Generated by Django 5.0.3 on 2024-04-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_car_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.FloatField(default=0.8, verbose_name='Объем'),
        ),
    ]
