# Generated by Django 5.0.3 on 2024-04-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_alter_car_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='title_model',
            field=models.CharField(null=True, unique=True, verbose_name='Модель'),
        ),
    ]
